language: cpp
os: linux
dist: bionic
<addons:
  apt:
    sources:
      - sourceline: "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main"
        key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
    packages:
      - clang-10
      - llvm-10-dev
      - libfl-dev
      - lcov

before_install:
  - CC=clang-10 && CXX=clang++-10
  - sudo update-alternatives --install /usr/bin/llvm-config llvm-config $(llvm-config-10 --bindir)/llvm-config 1
  - sudo update-alternatives --install /usr/bin/llvm-cov llvm-cov $(llvm-config-10 --bindir)/llvm-cov 1
  - export PATH=/usr/bin:$PATH

script:
  - make debug
  - ./cpcsc ./examples/comment.cpc
  - ./cpcsc ./examples/helloworld.cpc

after_success:
  - echo '#!/bin/bash' > llvm-gcov.sh && echo 'exec llvm-cov gcov "$@"' >> llvm-gcov.sh && chmod +x llvm-gcov.sh
  - lcov --gcov-tool "$(pwd)/llvm-gcov.sh" --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info
  - bash <(curl -s https://codecov.io/bash) -f coverage.info 